all:
	g++ -Wall -o distvec_20200422 distvec_20200422.cc
	g++ -Wall -o linkstate_20200422 linkstate_20200422.cc

dv :
	g++ -Wall -o distvec_20200422 distvec_20200422.cc

ls:
	g++ -Wall -o linkstate_20200422 linkstate_20200422.cc

clean:
	rm -f distvec_20200422 linkstate_20200422

fclean: clean
	rm -f output_dv.txt output_ls.txt

re: fclean all