# all:
# 	g++ -o -Wall distvec_20200422 distvec_20200422.cc 
# 	g++ -o -Wall linkstate_20200422 linkstate_20200422.cc

all:
	g++ -Wall distvec_20200422.cc -o distvec_20200422
#	g++ -Wall -std=c++11 linkstate_ref.cc -o linkstate

clean:
	rm -f distvec_20200422 linkstate_20200422

fclean: clean
	rm -f output_dv.txt output_ls.txt

re: fclean all